version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: kanban
    ports:
      - "8100:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:Z
      - ./kanban.html:/usr/share/nginx/html/kanban.html:Z
    restart: unless-stopped